# Generated by Django 3.1.7 on 2021-03-19 16:36

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xeber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoriya', models.CharField(choices=[('Xəbər', 'Xəbər'), ('İş elanları', (('Vakansiyalar', 'Vakansiyalar'), ('Təcrübə programları', 'Təcrübə programları'))), ('Təhsil', (('Universitetlər', 'Universitetlər'), ('Kolleclər', 'Kolleclər'), ('Xaricdə təhsil', 'Xaricdə təhsil'), ('Təqaüd programları', 'Təqaüd programları'))), ('Tədbirlər', (('Tədbirlər', 'Tədbirlər'), ('Təlimlər', 'Təlimlər'))), ('Məlumat bloku', 'Məlumat bloku')], max_length=25, verbose_name='Kategoriya')),
                ('sekil', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=80, size=[1280, 720], upload_to='images/')),
                ('basliq', models.CharField(max_length=40, verbose_name='Başlıq')),
            ],
        ),
    ]
