# Generated by Django 3.1.7 on 2021-03-30 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_auto_20210330_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='xeber',
            name='views',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Baxış sayı'),
        ),
        migrations.AlterField(
            model_name='xeber',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Istifadeci'),
        ),
    ]
