# Generated by Django 3.1.7 on 2021-03-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210330_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xeber',
            name='kategoriya',
            field=models.CharField(choices=[('Xəbər', 'Xəbər'), ('İş elanları', (('Vakansiyalar', 'Vakansiyalar'), ('Təcrübə programları', 'Təcrübə programları'))), ('Təhsil', (('Universitetlər', 'Universitetlər'), ('Universitet ixtisasları', 'Universitet ixtisasları'), ('Kolleclər', 'Kolleclər'), ('Kollec ixtisasları', 'Kollec ixtisasları'), ('Xaricdə təhsil', 'Xaricdə təhsil'), ('Təqaüd programları', 'Təqaüd programları'))), ('Tədbirlər', (('Tədbirlər', 'Tədbirlər'), ('Təlimlər', 'Təlimlər'))), ('Məlumat bloku', 'Məlumat bloku')], max_length=25, verbose_name='Kategoriya'),
        ),
    ]
