# Generated by Django 3.1.7 on 2021-03-31 12:22

from django.db import migrations
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210330_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinekitabxana',
            name='sekil',
            field=django_resized.forms.ResizedImageField(crop=None, default=django.utils.timezone.now, force_format='JPEG', keep_meta=True, quality=80, size=[1280, 720], upload_to='images/'),
            preserve_default=False,
        ),
    ]
