# Generated by Django 3.1.7 on 2021-04-04 21:57

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_onlinekitabxana_sekil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Başlıq')),
                ('sekil', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=80, size=[1280, 720], upload_to='images/')),
                ('posting_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kitab',
                'verbose_name_plural': 'Onlayn kitabxana',
            },
        ),
    ]
