# Generated by Django 3.1.7 on 2021-04-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Slide', 'verbose_name_plural': 'Slider'},
        ),
        migrations.AlterField(
            model_name='slider',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Başlıq'),
        ),
    ]
