# Generated by Django 3.1.7 on 2021-04-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20210405_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Link'),
        ),
    ]
