# Generated by Django 3.1.7 on 2021-04-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20210408_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobslider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Başlıq')),
                ('sekil', models.ImageField(upload_to='images/', verbose_name='Şəkil')),
                ('link', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Link')),
                ('posting_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mobil Slide',
                'verbose_name_plural': 'Mobil Slider',
            },
        ),
        migrations.AlterField(
            model_name='slider',
            name='sekil',
            field=models.ImageField(upload_to='images/', verbose_name='Şəkil'),
        ),
    ]
