# Generated by Django 3.1.7 on 2021-04-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20210409_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xeber',
            name='kategoriya',
            field=models.CharField(choices=[('Xəbər', 'Xəbər'), ('İş elanları', (('Vakansiyalar', 'Vakansiyalar'), ('Təcrübə programları', 'Təcrübə programları'))), ('Təhsil', (('Universitetlər', 'Universitetlər'), ('Universitet ixtisasları', 'Universitet ixtisasları'), ('Kolleclər', 'Kolleclər'), ('Kollec ixtisasları', 'Kollec ixtisasları'), ('Xaricdə təhsil', 'Xaricdə təhsil'), ('Təqaüd programları', 'Təqaüd programları'))), ('Tədbirlər', (('Tədbirlər', 'Tədbirlər'), ('Təlimlər', 'Təlimlər'))), ('Məlumat bloku', (('Front-end', 'Front-end'), ('Back-end', 'Back-end'), ('Full-stack', 'Full-stack'), ('IOS', 'IOS'), ('Android', 'Android'), ('Cross', 'Cross'), ('DevOps', 'DevOps'), ('Data analiz', 'Data analiz'), ('UX/UI', 'UX/UI'), ('Qrafik dizayn', 'Qrafik dizayn'), ('Sistem administratoru', 'Sistem administratoru'), ('Süni intellekt', 'Süni intellekt')))], max_length=25, verbose_name='Kategoriya'),
        ),
    ]
