# Generated by Django 3.1.7 on 2021-05-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20210409_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='reklamlar',
            name='ustreklamtxt1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Üst Mobil reklam text 1'),
        ),
        migrations.AddField(
            model_name='reklamlar',
            name='ustreklamtxt2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Üst Mobil reklam text 2'),
        ),
        migrations.AddField(
            model_name='reklamlar',
            name='ustreklamtxt3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Üst Mobil reklam text 3'),
        ),
    ]
