# Generated by Django 3.1.7 on 2021-05-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20210516_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobslider',
            name='txt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Metn'),
        ),
    ]
