# Generated by Django 3.1.7 on 2021-05-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_mobslider_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='txt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Metn'),
        ),
    ]
